### ISSUE TITLE
magit: git-commit-mode has to be removed

### ISSUE THREAD

**Issue by badmutex** [badi/dotfiles#10]
Closing of the magit pane results in:

```
Error (magit): git-commit-mode has to be removed

Magit is no longer compatible with the library `git-commit-mode',
which was used in earlier releases.  Please remove it, so that
Magit can use the successor `git-commit' without the obsolete
library getting in the way.  Then restart Emacs.
```

**Comment by badmutex** [comment]
Related to #11 

The [Magit manual] describes the procedure for upgrading from an older version.
Remove:
- `git-rebase-mode`
- `git-commit-mode`

In my installation, these are located in `~/.emacs.d/elpa`:

```
$ rm -r ~/.emacs.d/elpa/git-{commit,rebase}-mode-*
```

**Comment by cswarth** [comment]
For the sake of anyone else who lands here looking for clear instructions on how to fix this problem:
As stated above you need to manually remove from emacs lisp files.  The procedure below should help you find those files to remove.

You can find the source of a function definition with `M-x find-function`, e.g.

```
M-x find-function RET git-commit-mode RET
```

This placed me in a file `git-commit.el`.  View the directory listing where that files lives, `C-x F . RET`

Look through the directory listing for directories that have `git-commit-mode` and `git-rebase-mode` in their name.   In my case I had to change to the parent directory, `~/Library/Preferences/Aquamacs Emacs/Packages/elpa/` where I found, 

```
  drwxr-xr-x   7 cswarth  staff   238 Apr 22  2015 git-commit-mode-20150330.1048
  drwxr-xr-x   7 cswarth  staff   238 Mar  9  2015 git-rebase-mode-20150122.1114
```

These directories are out-of-date and should be removed.

Restart emacs and you should no longer see the error message.
